## Regenerate a clean, publication-style concentric STRING PPI figure.
##
## Usage:
##   Rscript scripts/03b_STRING_PPI_concentric_figure.R <results_dir> <output_dir>
##
## The input tables are generated by scripts/03_STRING_PPI_topology.R.

options(stringsAsFactors = FALSE)
if (.Platform$OS.type == "windows") {
  invisible(suppressWarnings(try(Sys.setlocale("LC_CTYPE", ".UTF-8"), silent=TRUE)))
}

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(igraph)
  library(ggraph)
  library(ggrepel)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Expected <results_dir> and <output_dir>.")
}

result_dir <- normalizePath(args[[1]], winslash = "/", mustWork = TRUE)
figure_dir <- normalizePath(args[[2]], winslash = "/", mustWork = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

label <- "main_75_common_targets"
candidate_genes <- c("BAX", "BCL2", "CDKN1A", "COL1A1", "CXCL8", "FN1", "TGFB1")
core_genes <- c("BCL2", "BAX", "FN1")

node_category <- function(genes) {
  category <- rep("Other common target", length(genes))
  category[genes %in% candidate_genes] <- "7-gene candidate"
  category[genes %in% core_genes] <- "Final core gene"
  factor(category, levels = c(
    "Other common target", "7-gene candidate", "Final core gene"
  ))
}

category_colors <- c(
  "Other common target" = "#4E79A7",
  "7-gene candidate" = "#F28E2B",
  "Final core gene" = "#E15759"
)

if (file.exists(file.path(result_dir, "submitted_75_PPI_nodes.csv"))) {
  metrics <- fread(file.path(result_dir, "submitted_75_PPI_nodes.csv"))
  edges <- fread(file.path(result_dir, "submitted_75_PPI_edges.csv"))
  # Match the original alphabetically ordered vertices for an identical layout.
  nodes <- data.table(name=sort(metrics$gene))
} else {
  nodes <- fread(file.path(result_dir, paste0(label, "_PPI_nodes.csv")))
  edges <- fread(file.path(result_dir, paste0(label, "_PPI_edges.csv")))
  metrics <- fread(file.path(result_dir, paste0(label, "_topology_metrics.csv")))
}
stopifnot(nrow(nodes)==75L, nrow(edges)==508L, !anyDuplicated(nodes[[1]]),
          all(c("gene","degree","MCC","mean_topology_rank","component_id","component_size") %in% names(metrics)),
          setequal(nodes[[1]],metrics$gene))

edges_for_graph <- edges[, .(from, to, weight = as.numeric(combined_score))]
g <- graph_from_data_frame(edges_for_graph, directed = FALSE, vertices = nodes)
node_df <- metrics[, .(
  name = gene, degree, MCC, mean_topology_rank, component_id, component_size
)]
V(g)$degree <- node_df$degree[match(V(g)$name, node_df$name)]
V(g)$MCC <- node_df$MCC[match(V(g)$name, node_df$name)]
V(g)$rank <- node_df$mean_topology_rank[match(V(g)$name, node_df$name)]
V(g)$component_size <- node_df$component_size[match(V(g)$name, node_df$name)]
V(g)$category <- node_category(V(g)$name)

comp <- components(g)
main_comp <- which.max(comp$csize)
main_nodes <- names(comp$membership)[comp$membership == main_comp]
hidden_nodes <- setdiff(V(g)$name, main_nodes)
g_main <- induced_subgraph(g, vids = main_nodes)

metrics_main <- copy(metrics[gene %in% main_nodes])
top_rank_genes <- metrics_main[order(mean_topology_rank, -degree, gene)]$gene
hub_genes <- head(top_rank_genes, min(18, length(top_rank_genes)))

set.seed(20260831)
base_layout <- as.data.table(create_layout(g_main, layout = "stress"))
base_layout[, name := as.character(name)]
base_layout <- merge(
  base_layout[, .(name, x, y)],
  metrics_main[, .(name = gene, degree, MCC, mean_topology_rank)],
  by = "name",
  all.x = TRUE
)
base_layout[, category := node_category(name)]
base_layout[, base_angle := atan2(y - mean(y), x - mean(x))]
base_layout[is.na(base_angle), base_angle := 0]
base_layout[, tier := fifelse(
  name %in% core_genes,
  "Final core genes",
  fifelse(
    name %in% candidate_genes | name %in% hub_genes,
    "Hub/candidate ring",
    fifelse(degree >= 12, "Intermediate ring", "Outer ring")
  )
)]
base_layout[, tier := factor(
  tier,
  levels = c("Final core genes", "Hub/candidate ring", "Intermediate ring", "Outer ring")
)]

assign_ring <- function(dt, radius, offset = 0) {
  dt <- copy(dt[order(base_angle, name)])
  if (nrow(dt) == 0) return(dt)
  dt[, theta := seq(0, 2 * pi, length.out = .N + 1)[seq_len(.N)] + offset]
  dt[, ring_radius := radius]
  dt
}

core_tbl <- copy(base_layout[tier == "Final core genes"])
if (nrow(core_tbl) > 0) {
  core_order <- c("BCL2", "FN1", "BAX")
  core_tbl[, core_rank := match(name, core_order)]
  core_tbl[is.na(core_rank), core_rank := .I + length(core_order)]
  setorder(core_tbl, core_rank)
  core_angles <- c(pi / 2, 7 * pi / 6, 11 * pi / 6)
  core_tbl[, theta := core_angles[seq_len(.N)]]
  core_tbl[, ring_radius := 0.38]
  core_tbl[, core_rank := NULL]
}

layout_tbl <- rbindlist(
  list(
    core_tbl,
    assign_ring(base_layout[tier == "Hub/candidate ring"], 1.17, offset = pi / 20),
    assign_ring(base_layout[tier == "Intermediate ring"], 1.88, offset = pi / 34),
    assign_ring(base_layout[tier == "Outer ring"], 2.62, offset = pi / 56)
  ),
  use.names = TRUE,
  fill = TRUE
)
layout_tbl[, x_plot := ring_radius * cos(theta)]
layout_tbl[, y_plot := ring_radius * sin(theta)]

edge_df <- as.data.table(as_data_frame(g_main, what = "edges"))
coord_df <- layout_tbl[, .(name, x_plot, y_plot)]
edge_df <- merge(edge_df, coord_df, by.x = "from", by.y = "name", all.x = TRUE)
setnames(edge_df, c("x_plot", "y_plot"), c("x_from", "y_from"))
edge_df <- merge(edge_df, coord_df, by.x = "to", by.y = "name", all.x = TRUE)
setnames(edge_df, c("x_plot", "y_plot"), c("x_to", "y_to"))

ring_df <- data.table(
  ring_radius = c(0.38, 1.17, 1.88, 2.62),
  ring_label = c("Final core genes", "Hub/candidate ring", "Intermediate ring", "Outer ring")
)

p <- ggplot() +
  geom_path(
    data = ring_df[, .(
      ring_radius,
      theta = seq(0, 2 * pi, length.out = 360)
    ), by = ring_label],
    aes(x = ring_radius * cos(theta), y = ring_radius * sin(theta)),
    color = "#D7DEE8",
    linewidth = 0.28,
    linetype = "dashed",
    alpha = 0.72
  ) +
  geom_segment(
    data = edge_df,
    aes(x = x_from, y = y_from, xend = x_to, yend = y_to,
        linewidth = weight, alpha = weight),
    color = "#98A4B0",
    lineend = "round",
    show.legend = FALSE
  ) +
  geom_point(
    data = layout_tbl,
    aes(x = x_plot, y = y_plot, size = degree, fill = category),
    shape = 21,
    color = "white",
    stroke = 0.68
  ) +
  ggrepel::geom_label_repel(
    data = layout_tbl,
    aes(x = x_plot, y = y_plot, label = name, color = category),
    size = 2.05,
    fontface = "bold",
    label.size = 0.12,
    label.padding = grid::unit(0.065, "lines"),
    label.r = grid::unit(0.06, "lines"),
    fill = grDevices::adjustcolor("white", alpha.f = 0.88),
    box.padding = 0.12,
    point.padding = 0.10,
    segment.color = "#7E8791",
    segment.size = 0.11,
    min.segment.length = 0,
    max.overlaps = Inf,
    seed = 20260831,
    show.legend = FALSE
  ) +
  scale_fill_manual(values = category_colors) +
  scale_color_manual(values = category_colors) +
  scale_linewidth_continuous(range = c(0.05, 0.42)) +
  scale_alpha_continuous(range = c(0.015, 0.15)) +
  scale_size_continuous(range = c(2.4, 8.4), breaks = c(10, 20, 30, 40)) +
  coord_equal(xlim = c(-3.38, 3.38), ylim = c(-3.05, 3.05), clip = "off") +
  labs(
    title = "STRING PPI network of 75 shared targets",
    subtitle = paste0(
      "Main connected component shown: ", length(main_nodes), "/", vcount(g),
      " nodes; concentric layout; node size = degree; STRING score >= 0.700"
    ),
    caption = if (length(hidden_nodes) > 0) {
      paste0(
        "Isolated nodes not shown in the main network layout: ",
        paste(sort(hidden_nodes), collapse = ", "),
        "."
      )
    } else {
      NULL
    }
  ) +
  guides(
    size = guide_legend(
      title = "Degree",
      order = 1,
      override.aes = list(
        shape = 21, fill = "#4E79A7", color = "white", alpha = 1, stroke = 0.55
      )
    ),
    fill = guide_legend(
      title = NULL,
      order = 2,
      override.aes = list(size = 5, shape = 21, color = "white", alpha = 1)
    )
  ) +
  theme_void(base_size = 12) +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 15),
    plot.subtitle = element_text(hjust = 0.5, color = "grey35", size = 9.2),
    plot.caption = element_text(hjust = 0.5, color = "grey45", size = 8.2),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    legend.box = "vertical",
    legend.spacing.x = grid::unit(0.34, "cm"),
    plot.margin = margin(6, 16, 8, 16)
  )

png_device <- if (requireNamespace("ragg", quietly = TRUE)) ragg::agg_png else NULL
stem <- file.path(figure_dir, paste0(label, "_STRING_PPI_network_concentric"))
ggsave(paste0(stem, ".png"), p, width = 9.2, height = 7.6, dpi = 320, device = png_device)
ggsave(paste0(stem, ".pdf"), p, width = 9.2, height = 7.6, device = grDevices::cairo_pdf)
ggsave(
  paste0(stem, "_publication.png"),
  p,
  width = 9.2,
  height = 7.6,
  dpi = 600,
  device = png_device
)

fwrite(
  layout_tbl[, .(gene = name, ring = as.character(tier), degree, x = x_plot, y = y_plot)],
  file.path(figure_dir, paste0(label, "_concentric_layout_coordinates.csv"))
)

cat("Saved concentric 75-gene PPI figure to: ", figure_dir, "\n", sep = "")
